id = "theme-lince"
name = "Lince Theme"
version = "0.0.1"
schema_version = 1
authors = ["Eduardo de Melo Xavier <xaviduds@gmail.com>"]
description = "Lince theme, black or white"
repository = "https://github.com/xaviduds/theme-lince"
